CREATE USER cars WITH PASSWORD 'cars';
CREATE DATABASE concessionaire;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO cars;
GRANT ALL PRIVILEGES ON DATABASE concessionaire TO cars;
ALTER USER cars WITH SUPERUSER;

